// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: proto/privacy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Privacy int32

const (
	Privacy_Unspecified Privacy = 0
	Privacy_Public      Privacy = 1
	Privacy_Friends     Privacy = 2
	Privacy_OnlyMe      Privacy = 3
)

// Enum value maps for Privacy.
var (
	Privacy_name = map[int32]string{
		0: "Unspecified",
		1: "Public",
		2: "Friends",
		3: "OnlyMe",
	}
	Privacy_value = map[string]int32{
		"Unspecified": 0,
		"Public":      1,
		"Friends":     2,
		"OnlyMe":      3,
	}
)

func (x Privacy) Enum() *Privacy {
	p := new(Privacy)
	*p = x
	return p
}

func (x Privacy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Privacy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_privacy_proto_enumTypes[0].Descriptor()
}

func (Privacy) Type() protoreflect.EnumType {
	return &file_proto_privacy_proto_enumTypes[0]
}

func (x Privacy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Privacy.Descriptor instead.
func (Privacy) EnumDescriptor() ([]byte, []int) {
	return file_proto_privacy_proto_rawDescGZIP(), []int{0}
}

var File_proto_privacy_proto protoreflect.FileDescriptor

var file_proto_privacy_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x3f, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79,
	0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x6e,
	0x6c, 0x79, 0x4d, 0x65, 0x10, 0x03, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x71, 0x2d, 0x71, 0x75, 0x6f, 0x63, 0x62, 0x61, 0x6e,
	0x67, 0x2f, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_privacy_proto_rawDescOnce sync.Once
	file_proto_privacy_proto_rawDescData = file_proto_privacy_proto_rawDesc
)

func file_proto_privacy_proto_rawDescGZIP() []byte {
	file_proto_privacy_proto_rawDescOnce.Do(func() {
		file_proto_privacy_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_privacy_proto_rawDescData)
	})
	return file_proto_privacy_proto_rawDescData
}

var file_proto_privacy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_privacy_proto_goTypes = []interface{}{
	(Privacy)(0), // 0: Privacy
}
var file_proto_privacy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_privacy_proto_init() }
func file_proto_privacy_proto_init() {
	if File_proto_privacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_privacy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_privacy_proto_goTypes,
		DependencyIndexes: file_proto_privacy_proto_depIdxs,
		EnumInfos:         file_proto_privacy_proto_enumTypes,
	}.Build()
	File_proto_privacy_proto = out.File
	file_proto_privacy_proto_rawDesc = nil
	file_proto_privacy_proto_goTypes = nil
	file_proto_privacy_proto_depIdxs = nil
}
